//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusDataProvider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpecialHireDBContext : DbContext
    {
        public SpecialHireDBContext()
            : base("name=SpecialHireDBContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public virtual DbSet<BookingInfo> BookingInfoes { get; set; }
        public virtual DbSet<BookingQuoteInfo> BookingQuoteInfoes { get; set; }
        public virtual DbSet<BookingTrailerInfo> BookingTrailerInfoes { get; set; }
        public virtual DbSet<BookingVehicleInfo> BookingVehicleInfoes { get; set; }
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<BusType> BusTypes { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        public virtual DbSet<PaymentTerm> PaymentTerms { get; set; }
        public virtual DbSet<Trailer> Trailers { get; set; }
        public virtual DbSet<TrailerType> TrailerTypes { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
