//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports.Services.AdministrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationFunctionality
    {
        public int ID { get; set; }
        public int ScreenID { get; set; }
        public string FunctionalityName { get; set; }
        public string FunctionalityCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ApplicationScreen ApplicationScreen { get; set; }
    }
}
