//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports.Services.AdministrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationScreen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationScreen()
        {
            this.ApplicationFunctionalities = new HashSet<ApplicationFunctionality>();
        }
    
        public int ID { get; set; }
        public int MenuID { get; set; }
        public string ScreenName { get; set; }
        public string ScreenCode { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationFunctionality> ApplicationFunctionalities { get; set; }
        public virtual ApplicationMenu ApplicationMenu { get; set; }
    }
}
