//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusFileImporter.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashierSigonSignoff
    {
        public int ID { get; set; }
        public string StaffNumber { get; set; }
        public Nullable<System.DateTime> SignOnDatTime { get; set; }
        public Nullable<System.DateTime> SignOffDateTime { get; set; }
        public string Activity { get; set; }
        public string CashInType { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public string DriverTotal { get; set; }
        public string CashCollected { get; set; }
        public string Shorts { get; set; }
        public Nullable<int> NetTickets { get; set; }
        public Nullable<int> NetPasses { get; set; }
        public Nullable<int> WaybillNumber { get; set; }
        public string CashierID { get; set; }
        public Nullable<System.DateTime> ImportDateTime { get; set; }
        public string Overs { get; set; }
        public string Terminal { get; set; }
    }
}
