//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusFileImporter.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Duty()
        {
            this.Journeys = new HashSet<Journey>();
        }
    
        public int id_Duty { get; set; }
        public int id_Module { get; set; }
        public int int4_DutyID { get; set; }
        public Nullable<int> int4_OperatorID { get; set; }
        public string str_ETMID { get; set; }
        public Nullable<int> int4_GTValue { get; set; }
        public Nullable<int> int4_NextTicketNumber { get; set; }
        public Nullable<int> int4_DutySeqNum { get; set; }
        public Nullable<System.DateTime> dat_DutyStartDate { get; set; }
        public Nullable<System.DateTime> dat_DutyStartTime { get; set; }
        public Nullable<System.DateTime> dat_DutyStopDate { get; set; }
        public Nullable<System.DateTime> dat_DutyStopTime { get; set; }
        public Nullable<System.DateTime> dat_TrafficDate { get; set; }
        public string str_BusID { get; set; }
        public Nullable<int> int4_DutyRevenue { get; set; }
        public Nullable<int> int4_DutyTickets { get; set; }
        public Nullable<int> int4_DutyPasses { get; set; }
        public Nullable<int> int4_DutyNonRevenue { get; set; }
        public Nullable<int> int4_DutyTransfer { get; set; }
        public string str_FirstRouteID { get; set; }
        public Nullable<short> int2_FirstJourneyID { get; set; }
        public Nullable<System.DateTime> dat_RecordMod { get; set; }
        public Nullable<int> id_BatchNo { get; set; }
        public Nullable<byte> byt_IeType { get; set; }
        public string str_EpromVersion { get; set; }
        public string str_OperatorVersion { get; set; }
        public string str_SpecialVersion { get; set; }
        public Nullable<int> int4_DutyAnnulCash { get; set; }
        public Nullable<int> int4_DutyAnnulCount { get; set; }
    
        public virtual Module Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journey> Journeys { get; set; }
    }
}
