//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusFileImporter.DataProvider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EbusImporterContext : DbContext
    {
        public EbusImporterContext()
            : base("name=EbusImporterContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Duty> Duties { get; set; }
        public virtual DbSet<GPSRecord> GPSRecords { get; set; }
        public virtual DbSet<Inspector> Inspectors { get; set; }
        public virtual DbSet<Journey> Journeys { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Module1> Modules1 { get; set; }
        public virtual DbSet<PosTran> PosTrans { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<Tran> Trans { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Waybill> Waybills { get; set; }
        public virtual DbSet<CashierDetail> CashierDetails { get; set; }
        public virtual DbSet<CashierStaffESN> CashierStaffESNs { get; set; }
        public virtual DbSet<CashierSigonSignoff> CashierSigonSignoffs { get; set; }
        public virtual DbSet<Cashier> Cashiers { get; set; }
    }
}
