//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusFileImporter.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPSRecord
    {
        public int id_GPSId { get; set; }
        public Nullable<int> id_Trans { get; set; }
        public Nullable<int> id_Stage { get; set; }
        public Nullable<int> id_Journey { get; set; }
        public Nullable<int> id_Duty { get; set; }
        public int id_Module { get; set; }
        public Nullable<int> int4_Type { get; set; }
        public Nullable<byte> int1_SatCount { get; set; }
        public Nullable<float> r_Lat { get; set; }
        public Nullable<float> r_Long { get; set; }
        public Nullable<int> int4_Distance { get; set; }
        public Nullable<short> int2_Speed { get; set; }
        public Nullable<int> int4_UpCount { get; set; }
        public Nullable<int> int4_DownCount { get; set; }
        public Nullable<System.DateTime> dat_GPSDateTime { get; set; }
        public Nullable<System.DateTime> dat_RecDateTime { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
