//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusFileImporter.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspector
    {
        public int id_Inspector { get; set; }
        public int id_Stage { get; set; }
        public int id_InspectorID { get; set; }
        public Nullable<System.DateTime> datTimeStamp { get; set; }
    
        public virtual Stage Stage { get; set; }
    }
}
