//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusFileImporter.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journey()
        {
            this.Stages = new HashSet<Stage>();
        }
    
        public int id_Journey { get; set; }
        public int id_Duty { get; set; }
        public int id_Module { get; set; }
        public string str_RouteID { get; set; }
        public Nullable<short> int2_JourneyID { get; set; }
        public Nullable<short> int2_Direction { get; set; }
        public Nullable<System.DateTime> dat_JourneyStartDate { get; set; }
        public Nullable<System.DateTime> dat_JourneyStartTime { get; set; }
        public Nullable<System.DateTime> dat_JourneyStopDate { get; set; }
        public Nullable<System.DateTime> dat_JourneyStopTime { get; set; }
        public Nullable<System.DateTime> dat_TrafficDate { get; set; }
        public Nullable<int> int4_Distance { get; set; }
        public Nullable<int> int4_Traveled { get; set; }
        public Nullable<int> int4_JourneyRevenue { get; set; }
        public Nullable<int> int4_JourneyTickets { get; set; }
        public Nullable<int> int4_JourneyPasses { get; set; }
        public Nullable<int> int4_JourneyNonRevenue { get; set; }
        public Nullable<int> int4_JourneyTransfer { get; set; }
        public Nullable<System.DateTime> dat_RecordMod { get; set; }
        public Nullable<int> id_BatchNo { get; set; }
        public Nullable<byte> byt_IeType { get; set; }
        public Nullable<System.DateTime> dat_JourneyMoveTime { get; set; }
        public Nullable<System.DateTime> dat_JourneyArrivalTime { get; set; }
        public Nullable<int> int4_GPSDistance { get; set; }
    
        public virtual Duty Duty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stage> Stages { get; set; }
    }
}
