//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusFileImporter.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module1
    {
        public int id_Module { get; set; }
        public string str6_Modules { get; set; }
        public Nullable<byte> int_ModuleStatus { get; set; }
        public byte int_ModuleType { get; set; }
        public int int_ModuleSerial { get; set; }
        public System.DateTime dat_FirstUsed { get; set; }
        public System.DateTime dat_LastUsed { get; set; }
    }
}
