//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusFileImporter.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int int4_StaffID { get; set; }
        public string str50_StaffName { get; set; }
        public bool bit_InUse { get; set; }
        public Nullable<System.DateTime> dat_RecordMod { get; set; }
        public int int4_StaffTypeID { get; set; }
        public int int4_StaffSubTypeID { get; set; }
        public string str4_LocationCode { get; set; }
        public string str2_LocationCode { get; set; }
        public string SerialNumber { get; set; }
    }
}
